name: "Open Github Issue"
author: Juan
description: "Opens a github issue"
inputs:
  token:
    description: "Github Token"
    required: true
  title:
    description: "Issue title"
    required: true
  body:
    description: "Issue body"
    required: false
  assignees:
    description: "Issue Assignees"
    required: false
outputs:
  issue: # id pf putput
    description: "the issue object"
runs:
  using: "node12"
  main: "dist/index.js"
